[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "campermit"
version = "0.1.0"
description = "A Linux CLI utility for controlling camera availability at the device and driver level."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    {name = "Goutham Krishna P"}
]
dependencies = []

[project.scripts]
campermit = "campermit.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
